### ISSUE TITLE
Broken deployment when upgraded CLI

### ISSUE THREAD

**Issue by iBobik** [contember/contember#477]
Hello,
I upgraded CLI in CI from 1.1.2 to 1.3.0-rc.2, my .gitlab-ci.yml looks like:
```
contember cloud deploy:
  stage: deploy
  image:
    name: contember/cli:1.3.0-rc.2
    entrypoint: [""]
  services:
    - docker:dind
  script:
    - cd contember
    - contember deploy contember://${CONTEMBER_PROJECT}:${CONTEMBER_TOKEN}@${CONTEMBER_PROJECT}.eu.contember.cloud --yes
  environment:
    name: production
  only:
    - master

```
At first it failed on:
```
Package @contember/schema defined in package.json is not installed.
Package @contember/schema-definition defined in package.json is not installed.
Please make sure all dependencies are up to date.
If you are really certain about the compatibility, you can disable this version check by running the CLI with the CONTEMBER_SKIP_VERSION_CHECK=1 environment variable
```
I haven't called `npm i` because it is expensive and not needed for engine deployment. Solved it by CONTEMBER_SKIP_VERSION_CHECK, but it would be nice to have version check without install.

Then it failed on:
```
Please specify a local name project
```
But it is specified in the DSN.
